# Generated by Django 5.2.7 on 2025-11-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='calculated_rating',
            field=models.FloatField(default=0, verbose_name='Общая оценка'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_freshness',
            field=models.IntegerField(choices=[(5, 'Максимальная свежесть'), (4, 'Очень свежие'), (3, 'Средняя свежесть'), (2, 'Не очень свежие'), (1, 'Несвежие')], default=3, verbose_name='Свежесть продуктов'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_quality',
            field=models.IntegerField(choices=[(5, 'Отличное'), (4, 'Хорошее'), (3, 'Удовлетворительное'), (2, 'Плохое'), (1, 'Очень плохое')], default=3, verbose_name='Качество продуктов'),
        ),
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.IntegerField(choices=[(5, 'Определенно да'), (4, 'Вероятно да'), (3, 'Не уверен(а)'), (2, 'Вероятно нет'), (1, 'Определенно нет')], default=3, verbose_name='Рекомендация друзьям'),
        ),
        migrations.AddField(
            model_name='review',
            name='service_quality',
            field=models.IntegerField(choices=[(5, 'Идеальный сервис'), (4, 'Очень хороший'), (3, 'Нормальный'), (2, 'Плохой'), (1, 'Очень плохой')], default=3, verbose_name='Качество обслуживания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Ваши впечатления'),
        ),
    ]
