# Generated by Django 5.2.7 on 2025-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('vegetables', 'Овощи'), ('fruits', 'Фрукты'), ('dairy', 'Молочные продукты'), ('meat', 'Мясо и птица')], max_length=20, verbose_name='Категория')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('image', models.URLField(max_length=500, verbose_name='Изображение')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес/объем')),
                ('shelf_life', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок годности')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна происхождения')),
                ('quality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Качество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
