# Generated by Django 5.2.7 on 2025-12-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.IntegerField(help_text='Например: 10 для 10% скидки', verbose_name='Процент скидки'),
        ),
    ]
