# Generated by Django 5.2.7 on 2025-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_promocode_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_lon',
        ),
    ]
